### ISSUE TITLE
Problem data

### ISSUE THREAD

**Issue by ecto0310** [ecto0310/can_you_say#4]
# Task
- [x] Add problem data.
  - [x] Element
  - [x] JR Joban Line
  - [x] JR Yamanote Line
